vich_uploader:
    db_driver: orm
    mappings:
        mes_documents:
            uri_prefix: '%app.path.featured_document%'
            upload_destination: '%kernel.project_dir%/public%app.path.featured_document%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            # inject_on_load: false
            # delete_on_update: false
            # delete_on_remove: false
            
        mes_photos:
            uri_prefix: '%app.path.featured_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.featured_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false